# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - entity-extractor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://utilitymarketplace.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b5b6cc629bdd459f9d357a582b216bf7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_111bb7a165e24bb6b6fc681ba646224e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: utilitymarketplace.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b5b6cc629bdd459f9d357a582b216bf7 }}/entityextractor:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'entity-extractor'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9f6432fe61884d8cae4e829f6af43369 }}
        images: 'utilitymarketplace.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b5b6cc629bdd459f9d357a582b216bf7 }}/entityextractor:${{ github.sha }}'